# NOTE: Generated By HttpRunner v3.1.6
# FROM: 2022-9-20.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT2022920(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/auth/oauth2/token")
            .post("http://58.49.165.22:8062/auth/oauth2/token")
            .with_params(
                **{
                    "code": "",
                    "grant_type": "password",
                    "randomStr": "",
                    "scope": "server",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Authorization": "Basic cGlnOnBpZw==",
                    "Connection": "keep-alive",
                    "Content-Length": "45",
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Host": "58.49.165.22:8062",
                    "Origin": "http://58.49.165.22:8062",
                    "Referer": "http://58.49.165.22:8062/",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
                    "isToken": "false",
                }
            )
            .with_data({"password": "YehdBPev", "username": "91341600MA2MXAHD26"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.sub", "91341600MA2MXAHD26")
            .assert_equal("body.clientId", "pig")
            .assert_equal("body.iss", "https://pig4cloud.com")
            .assert_equal("body.token_type", "Bearer")
            .assert_equal("body.license", "https://pig4cloud.com")
            .assert_equal("body.expires_in", 43200)
        ),
    ]


if __name__ == "__main__":
    TestCaseT2022920().test_start()
